name: Build Tweak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          echo "GH_THEOS=$HOME/theos" >> $GITHUB_ENV
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master/* $HOME/theos/sdks/
          rm -rf master.zip sdks-master

      - name: Build Package
        run: |
          export THEOS=$GH_THEOS
          make package FINALPACKAGE=1

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: InstaSRT-Output
          path: |
            packages/*.deb
            .theos/obj/debug/*.dylib
            .theos/obj/*.dylib
